### ISSUE TITLE
Move onset_detect.py to somewhere more sensible

### ISSUE THREAD

**Issue by jalfje** [isaacormack/Tabber#57]
Right now (on feature/tabbing) it's in the `crepe/` directory, which is not only a misnomer, but is also where output files go. It should probably go in the `src/tabbing` directory, though I'm not sure about that simply because it's a python file, not a tsx file. That probably makes the most sense, though.

**Comment by isaaccormack** [comment]
Maybe `server/tabbing/`? I think `server/src/` should be reserved for the web app code.

I think that even if its in `src/` with the .tsx files, this wont effect builds or anything as TypeScript only looks for .ts or .tsx files.

**Comment by jalfje** [comment]
I think I'll move it to `server/src/tabbing`, along with the rest of the tabbing code. You're right, TypeScript will ignore it. It makes sense to be there, too, as it is code that performs a core functionality of the webapp.

**Comment by jalfje** [comment]
Actually, on second thought, that doesn't quite make sense, as `server/src` isn't really meant to be deployed. `server/tabbing` does make more sense.
