### ISSUE TITLE
Add "regenerate tab" button to edit page

### ISSUE THREAD

**Issue by jalfje** [isaacormack/Tabber#60]
Regenerate tab based on updated tuning and capo, or to fix errors in user modification of a tab.

**Comment by isaaccormack** [comment]
> or to fix errors in user modification of a tab.

What do you mean exactly by this?

As I understand it, you mean if a user changes their tab on the client side, then saves it back to the database, then wants to reset their tab back to its initial tabbing they would re-tab it?

**Comment by jalfje** [comment]
> As I understand it, you mean if a user changes their tab on the client side, then saves it back to the database, then wants to reset their tab back to its initial tabbing they would re-tab it?

Yeah, just that
